version: '3.1'

services:
  kitab-mailhog:
    image: phpdockerio/mailhog:latest
    container_name: kitab-mailhog
    ports:
      - "8125:8025"

  kitab-mongo:
    image: mongo:4.2-bionic
    container_name: kitab-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
        - ../mongodb:/data/db
        - ./mongo/prod:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

  # kitab-nginx:
  #   image: phpdockerio/nginx:latest
  #   container_name: kitab-nginx
  #   volumes:
  #       - ..:/var/www/kitab
  #       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #    - "8180:80"
  #   links:
  #    - kitab-php-fpm
  #
  # kitab-php-fpm:
  #   build: .
  #   dockerfile: php-fpm/Dockerfile
  #   container_name: kitab-php-fpm
  #   volumes:
  #     - ..:/var/www/kitab
  #     - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  #   links:
  #     - kitab-mailhog
  #     - kitab-mysql
