###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

kitab-mailhog:
  container_name: kitab-dev-mailhog
  ports:
    - "9125:8025"

kitab-mysql:
  container_name: kitab-dev-mysql
  volumes:
      - ../sql/dev:/docker-entrypoint-initdb.d
  ports:
    - "9106:3306"

kitab-nginx:
  container_name: kitab-dev-nginx
  ports:
   - "9180:80"

kitab-php-fpm:
  container_name: kitab-dev-php-fpm

