###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

kitab-mailhog:
  image: phpdockerio/mailhog:latest
  container_name: kitab-mailhog
  ports:
    - "8125:8025"

kitab-mysql:
  image: mysql:5.7
  container_name: kitab-mysql
  volumes:
      - ../mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ../sql/prod:/docker-entrypoint-initdb.d
  ports:
    - "8106:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}

kitab-nginx:
  image: nginx:alpine
  container_name: kitab-nginx
  volumes:
      - ..:/var/www/kitab
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8180:80"
  links:
   - kitab-php-fpm

kitab-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: kitab-php-fpm
  volumes:
    - ..:/var/www/kitab
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - kitab-mailhog
    - kitab-mysql
