version: '3.1'

services:
  kitab-mailhog:
    image: phpdockerio/mailhog:latest
    container_name: kitab-mailhog
    ports:
      - "8125:8025"

  kitab-mongo:
    image: mongo:4.2-bionic
    container_name: kitab-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
        - ../mongodb:/data/db
        - ./mongo/prod:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
