version: '3.1'

services:
  kitab-mailhog:
    image: phpdockerio/mailhog:latest
    container_name: kitab-mailhog
    ports:
      - "8125:8025"

 kitab-mongo:
    volumes:
        - ../mongodb-dev:/data/db
        - ./mongo/dev:/docker-entrypoint-initdb.d
